name: mix_tailwinds
description: Tailwind-like class utilities mapped to Mix 2.0 stylers.
version: 0.1.0-dev.0
publish_to: "none"

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.1"

dependencies:
  flutter:
    sdk: flutter
  mix: ^2.0.0-dev.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
