name: mix_generator
description: A code generator for Mix, an expressive way to effortlessly build design systems in Flutter.
version: 2.0.0-rc.1
homepage: https://github.com/btwld/mix
repository: https://github.com/btwld/mix/tree/main/packages/mix_generator

environment:
  sdk: ">=3.10.0 <4.0.0"
  
dependencies:
  mix_annotations: ^2.0.0-rc.1
  dart_style: ^3.0.0
  collection: ^1.15.0
  source_gen: ">=3.0.0 <5.0.0"
  analyzer: '>=9.0.0 <11.0.0'
  build: ">=3.0.0 <5.0.0"
  build_config: ^1.1.0
  logging: ^1.2.0
  path: ^1.8.3

dev_dependencies:
  test: ^1.24.4
  build_runner: ^2.11.0
  build_test: ^3.5.5
  source_gen_test: ^1.3.4
  # Lint
  dart_code_metrics_presets: ^2.24.0
  flutter_lints: ^6.0.0
